server:
  port: 8201
spring:
  application:
    name: bookservice
  datasource:
    password: mysql
    username: root
    url: jdbc:mysql://localhost:3306/cloudstudy
eureka:
  client:
    service-url:
      # 将两个Eureka的地址都加入，这样就算有一个Eureka挂掉，也能完成注册
      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka