server:
  port: 8201
spring:
  application:
    name: book-service
  datasource:
    password: mysql
    username: root
    url: jdbc:mysql://localhost:3306/cloudstudy
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        namespace: 603b5562-5e3c-4905-bb52-c4a4bbf662a7