server:
  port: 8301
spring:
  application:
    name: borrow-service
  datasource:
    password: mysql
    username: root
    url: jdbc:mysql://localhost:3306/cloudstudy
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        ephemeral: false
        cluster-name: XiAn
        namespace: 603b5562-5e3c-4905-bb52-c4a4bbf662a7
    loadbalancer:
      nacos:
        enabled: true

